### ISSUE TITLE
[FIX] Thunar as a root

### ISSUE THREAD

**Issue by Akash6222** [tcet-opensource/tcet-linux#103]
In thunar when we select option ` Open Thunar As Root ` then window size one new window is different than actual one and terminal font and colors are different
- [ ] Fix window size
- [ ] Fix font and background of terminal

**Comment by Akash6222** [comment]
![2023-09-06T12:45:01,937498620+05:30](https://github.com/tcet-opensource/tcet-linux/assets/101584901/370c6284-f779-454c-8ae2-e87e9fb2b86b)

**Comment by Akash6222** [comment]
https://github.com/tcet-opensource/tcet-linux/tree/main/airootfs/root/.config

**Comment by VinayChaurasiyaA** [comment]
- after looking at file system, i belive that this  issue is not something  because of thunar, it may be because of font's being applied to only the local user and not the whole system (root)
![image](https://github.com/tcet-opensource/tcet-linux/assets/92705023/a93c3257-9bc2-4219-aa17-14a1993c9c93)

**Comment by beans9926** [comment]
I have just worked on the terminal issue in branch #105 and pushed the necessary changes. You can continue working on just the Thunar part.

The rest, we will take a look at later

**Comment by VinayChaurasiyaA** [comment]
@Akash6222 This issue should be closed! as we have already worked on thunar part
